(setq perldoc-obarray (make-vector 1519 nil))
;; Functions
(mapc (lambda (func)
         (set (intern func perldoc-obarray) t))
'(
"*" "-A" "-B" "-C" "-M" "-O" "-R" "-S" "-T" "-W" "-X" "-b" "-c" "-d" "-e"
"-f" "-g" "-k" "-l" "-o" "-p" "-r" "-s" "-t" "-u" "-w" "-x" "-z"
"Otherwise," "Otherwise:" "abs" "accept" "alarm" "atan2" "bind" "binmode"
"bless" "break" "caller" "chdir" "chmod" "chomp" "chop" "chown" "chr"
"chroot" "close" "closedir" "connect" "continue" "cos" "crypt" "dbmclose"
"dbmopen" "defined" "delete" "die" "do" "dump" "each" "endgrent"
"endhostent" "endnetent" "endprotoent" "endpwent" "endservent" "eof" "eval"
"exec" "exists" "exit" "exp" "fcntl" "fileno" "flock" "fork" "format"
"formline" "getc" "getgrent" "getgrgid" "getgrnam" "gethostbyaddr"
"gethostbyname" "gethostent" "getlogin" "getnetbyaddr" "getnetbyname"
"getnetent" "getpeername" "getpgrp" "getppid" "getpriority"
"getprotobyname" "getprotobynumber" "getprotoent" "getpwent" "getpwnam"
"getpwuid" "getservbyname" "getservbyport" "getservent" "getsockname"
"getsockopt" "glob" "gmtime" "goto" "grep" "hex" "import" "index" "int"
"ioctl" "join" "keys" "kill" "last" "lc" "lcfirst" "length" "link" "listen"
"local" "localtime" "lock" "log" "lstat" "m" "map" "mkdir" "msgctl"
"msgget" "msgrcv" "msgsnd" "my" "next" "no" "oct" "open" "opendir" "ord"
"our" "pack" "package" "pipe" "pop" "pos" "print" "printf" "prototype"
"push" "q" "qq" "qr" "quotemeta" "qw" "qx" "rand" "read" "readdir"
"readline" "readlink" "readpipe" "recv" "redo" "ref" "rename" "require"
"reset" "return" "reverse" "rewinddir" "rindex" "rmdir" "s" "say" "scalar"
"seek" "seekdir" "select" "semctl" "semget" "semop" "send" "setgrent"
"sethostent" "setnetent" "setpgrp" "setpriority" "setprotoent" "setpwent"
"setservent" "setsockopt" "shift" "shmctl" "shmget" "shmread" "shmwrite"
"shutdown" "sin" "sleep" "socket" "socketpair" "sort" "splice" "split"
"sprintf" "sqrt" "srand" "stat" "state" "study" "sub" "substr" "symlink"
"syscall" "sysopen" "sysread" "sysseek" "system" "syswrite" "tell"
"telldir" "tie" "tied" "time" "times" "tr" "truncate" "uc" "ucfirst"
"umask" "undef" "unlink" "unpack" "unshift" "untie" "use" "utime" "values"
"vec" "wait" "waitpid" "wantarray" "warn" "write" "y"))

;; Modules
(mapc (lambda (mod)
         (intern mod perldoc-obarray))
'(
"AE" "AnyDBM_File" "AnyEvent" "AnyEvent::AIO" "AnyEvent::BDB"
"AnyEvent::DNS" "AnyEvent::Debug" "AnyEvent::Handle" "AnyEvent::Impl::EV"
"AnyEvent::Impl::Event" "AnyEvent::Impl::EventLib" "AnyEvent::Impl::Glib"
"AnyEvent::Impl::IOAsync" "AnyEvent::Impl::Irssi" "AnyEvent::Impl::POE"
"AnyEvent::Impl::Perl" "AnyEvent::Impl::Qt" "AnyEvent::Impl::Tk"
"AnyEvent::Intro" "AnyEvent::Socket" "AnyEvent::Strict" "AnyEvent::TLS"
"AnyEvent::Util" "Async::MergePoint" "Attribute::Handlers" "Authen::SASL"
"Authen::SASL::CRAM_MD5" "Authen::SASL::EXTERNAL" "Authen::SASL::Perl"
"Authen::SASL::Perl::ANONYMOUS" "Authen::SASL::Perl::CRAM_MD5"
"Authen::SASL::Perl::DIGEST_MD5" "Authen::SASL::Perl::EXTERNAL"
"Authen::SASL::Perl::GSSAPI" "Authen::SASL::Perl::LOGIN"
"Authen::SASL::Perl::PLAIN" "AutoLoader" "AutoSplit" "B" "B::Concise"
"B::Debug" "B::Deparse" "B::Lint" "B::Lint::Debug" "B::Showlex" "B::Terse"
"B::Xref" "BDB" "Benchmark" "Bundle::DBI" "Bundle::LWP" "CORE" "Carp"
"Carp::Heavy" "Class::Struct" "Compress::Raw::Bzip2" "Compress::Raw::Zlib"
"Compress::Zlib" "Config" "Config::Extensions" "Coro" "Coro::AIO"
"Coro::AnyEvent" "Coro::BDB" "Coro::Channel" "Coro::Debug" "Coro::EV"
"Coro::Event" "Coro::Handle" "Coro::Intro" "Coro::LWP" "Coro::MakeMaker"
"Coro::RWLock" "Coro::Select" "Coro::Semaphore" "Coro::SemaphoreSet"
"Coro::Signal" "Coro::Socket" "Coro::Specific" "Coro::State"
"Coro::Storable" "Coro::Timer" "Coro::Util" "Curses" "Cwd" "DB" "DBD::DBM"
"DBD::ExampleP" "DBD::File" "DBD::File::Developers" "DBD::File::HowTo"
"DBD::File::Roadmap" "DBD::Gofer" "DBD::Gofer::Policy::Base"
"DBD::Gofer::Policy::classic" "DBD::Gofer::Policy::pedantic"
"DBD::Gofer::Policy::rush" "DBD::Gofer::Transport::Base"
"DBD::Gofer::Transport::corostream" "DBD::Gofer::Transport::null"
"DBD::Gofer::Transport::pipeone" "DBD::Gofer::Transport::stream"
"DBD::NullP" "DBD::Proxy" "DBD::SQLite" "DBD::SQLite::Cookbook"
"DBD::Sponge" "DBI" "DBI::Changes" "DBI::Const::GetInfo::ANSI"
"DBI::Const::GetInfo::ODBC" "DBI::Const::GetInfoReturn"
"DBI::Const::GetInfoType" "DBI::DBD" "DBI::DBD::Metadata"
"DBI::DBD::SqlEngine" "DBI::DBD::SqlEngine::Developers"
"DBI::DBD::SqlEngine::HowTo" "DBI::FAQ" "DBI::Gofer::Execute"
"DBI::Gofer::Request" "DBI::Gofer::Response" "DBI::Gofer::Serializer::Base"
"DBI::Gofer::Serializer::DataDumper" "DBI::Gofer::Serializer::Storable"
"DBI::Gofer::Transport::Base" "DBI::Gofer::Transport::pipeone"
"DBI::Gofer::Transport::stream" "DBI::Profile" "DBI::ProfileData"
"DBI::ProfileDumper" "DBI::ProfileDumper::Apache" "DBI::ProfileSubs"
"DBI::ProxyServer" "DBI::PurePerl" "DBI::SQL::Nano"
"DBI::Util::CacheMemory" "DBI::Util::_accessor" "DBM_Filter"
"DBM_Filter::compress" "DBM_Filter::encode" "DBM_Filter::int32"
"DBM_Filter::null" "DBM_Filter::utf8" "DB_File" "Data::Dumper"
"Devel::DProf" "Devel::InnerPackage" "Devel::PPPort" "Devel::Peek"
"Devel::SelfStubber" "Digest" "Digest::HMAC" "Digest::HMAC_MD5"
"Digest::HMAC_SHA1" "Digest::MD5" "Digest::SHA1" "Digest::base"
"Digest::file" "DirHandle" "Dumpvalue" "DynaLoader" "EV" "EV::MakeMaker"
"EV::libev" "Encode" "Encode::Alias" "Encode::Byte" "Encode::CJKConstants"
"Encode::CN" "Encode::CN::HZ" "Encode::Config" "Encode::EBCDIC"
"Encode::Encoder" "Encode::Encoding" "Encode::GSM0338" "Encode::Guess"
"Encode::JP" "Encode::JP::H2Z" "Encode::JP::JIS7" "Encode::KR"
"Encode::KR::2022_KR" "Encode::MIME::Header"
"Encode::MIME::Header::ISO_2022_JP" "Encode::MIME::Name" "Encode::Symbol"
"Encode::TW" "Encode::Unicode" "Encode::Unicode::UTF7" "English" "Env"
"Errno" "Error" "Error::Simple" "Event" "Event::Lib" "Event::MakeMaker"
"Event::Watcher" "Event::generic" "Event::group" "Event::idle" "Event::io"
"Event::signal" "Event::timer" "Event::type" "Event::var" "Exporter"
"Exporter::Heavy" "ExtUtils::Command" "ExtUtils::Constant"
"ExtUtils::Constant::Base" "ExtUtils::Constant::ProxySubs"
"ExtUtils::Constant::Utils" "ExtUtils::Constant::XS" "ExtUtils::Miniperl"
"Fatal" "Fcntl" "File::Basename" "File::CheckTree" "File::Compare"
"File::Copy" "File::DosGlob" "File::Find" "File::Glob" "File::GlobMapper"
"File::Listing" "File::Path" "File::Spec" "File::Spec::Cygwin"
"File::Spec::Epoc" "File::Spec::Functions" "File::Spec::Mac"
"File::Spec::OS2" "File::Spec::Unix" "File::Spec::VMS" "File::Spec::Win32"
"File::Temp" "File::stat" "FileCache" "FileHandle" "Filter::Simple"
"Filter::Util::Call" "FindBin" "GDBM_File" "GSSAPI" "GSSAPI::OID"
"GSSAPI::OID::Set" "GSSAPI::Status" "Getopt::Long" "Getopt::Std" "Git"
"Glib" "Glib::BookmarkFile" "Glib::Boxed" "Glib::CodeGen" "Glib::Error"
"Glib::Flags" "Glib::GenPod" "Glib::Install::Files" "Glib::KeyFile"
"Glib::Log" "Glib::MainLoop" "Glib::Markup" "Glib::Object"
"Glib::Object::Subclass" "Glib::OptionContext" "Glib::OptionGroup"
"Glib::Param::Boolean" "Glib::Param::Double" "Glib::Param::Enum"
"Glib::Param::Flags" "Glib::Param::Int" "Glib::Param::Int64"
"Glib::Param::String" "Glib::Param::UInt" "Glib::Param::UInt64"
"Glib::Param::Unichar" "Glib::ParamSpec" "Glib::ParseXSDoc" "Glib::Signal"
"Glib::Type" "Glib::Utils" "Glib::index" "Glib::version" "Guard"
"HTML::Entities" "HTML::Filter" "HTML::Form" "HTML::HeadParser"
"HTML::LinkExtor" "HTML::Parser" "HTML::PullParser" "HTML::Tagset"
"HTML::TokeParser" "HTTP::Config" "HTTP::Cookies"
"HTTP::Cookies::Microsoft" "HTTP::Cookies::Netscape" "HTTP::Daemon"
"HTTP::Date" "HTTP::Headers" "HTTP::Headers::Auth" "HTTP::Headers::ETag"
"HTTP::Headers::Util" "HTTP::Message" "HTTP::Negotiate" "HTTP::Request"
"HTTP::Request::Common" "HTTP::Response" "HTTP::Status" "Hash::Util"
"Hash::Util::FieldHash" "Heap" "Heap::Binary" "Heap::Binomial" "Heap::Elem"
"Heap::Elem::Num" "Heap::Elem::NumRev" "Heap::Elem::Ref"
"Heap::Elem::RefRev" "Heap::Elem::Str" "Heap::Elem::StrRev"
"Heap::Fibonacci" "I18N::Collate" "I18N::LangTags" "I18N::LangTags::Detect"
"I18N::LangTags::List" "I18N::Langinfo" "IO" "IO::AIO" "IO::Async"
"IO::Async::ChildManager" "IO::Async::Connector" "IO::Async::DetachedCode"
"IO::Async::DetachedCode::FlatMarshaller"
"IO::Async::DetachedCode::StorableMarshaller" "IO::Async::Handle"
"IO::Async::Internals::SignalProxy" "IO::Async::Internals::TimeQueue"
"IO::Async::Listener" "IO::Async::Loop" "IO::Async::Loop::IO_Poll"
"IO::Async::Loop::Poll" "IO::Async::Loop::Select" "IO::Async::LoopTests"
"IO::Async::MergePoint" "IO::Async::Notifier" "IO::Async::Resolver"
"IO::Async::Sequencer" "IO::Async::Signal" "IO::Async::Stream"
"IO::Async::Test" "IO::Async::Timer" "IO::Async::Timer::Countdown"
"IO::Async::Timer::Periodic" "IO::Compress::Adapter::Bzip2"
"IO::Compress::Adapter::Deflate" "IO::Compress::Adapter::Identity"
"IO::Compress::Base" "IO::Compress::Base::Common" "IO::Compress::Bzip2"
"IO::Compress::Deflate" "IO::Compress::FAQ" "IO::Compress::Gzip"
"IO::Compress::Gzip::Constants" "IO::Compress::RawDeflate"
"IO::Compress::Zip" "IO::Compress::Zip::Constants"
"IO::Compress::Zlib::Constants" "IO::Compress::Zlib::Extra" "IO::Dir"
"IO::File" "IO::Handle" "IO::Pipe" "IO::Poll" "IO::Pty" "IO::Seekable"
"IO::Select" "IO::Socket" "IO::Socket::INET" "IO::Socket::SSL"
"IO::Socket::UNIX" "IO::Tty" "IO::Tty::Constant"
"IO::Uncompress::Adapter::Bunzip2" "IO::Uncompress::Adapter::Identity"
"IO::Uncompress::Adapter::Inflate" "IO::Uncompress::AnyInflate"
"IO::Uncompress::AnyUncompress" "IO::Uncompress::Base"
"IO::Uncompress::Bunzip2" "IO::Uncompress::Gunzip"
"IO::Uncompress::Inflate" "IO::Uncompress::RawInflate"
"IO::Uncompress::Unzip" "IPC::Msg" "IPC::Open2" "IPC::Open3"
"IPC::Semaphore" "IPC::SharedMem" "IPC::SysV" "LWP" "LWP::Authen::Basic"
"LWP::Authen::Digest" "LWP::Authen::Ntlm" "LWP::ConnCache" "LWP::Debug"
"LWP::DebugFile" "LWP::MediaTypes" "LWP::MemberMixin" "LWP::Protocol"
"LWP::Protocol::GHTTP" "LWP::Protocol::cpan" "LWP::Protocol::data"
"LWP::Protocol::file" "LWP::Protocol::ftp" "LWP::Protocol::gopher"
"LWP::Protocol::http" "LWP::Protocol::http10" "LWP::Protocol::https"
"LWP::Protocol::https10" "LWP::Protocol::loopback" "LWP::Protocol::mailto"
"LWP::Protocol::nntp" "LWP::Protocol::nogo" "LWP::RobotUA" "LWP::Simple"
"LWP::UserAgent" "List::Util" "List::Util::PP" "List::Util::XS"
"Locale::Constants" "Locale::Country" "Locale::Currency" "Locale::Language"
"Locale::Maketext" "Locale::Maketext::Guts" "Locale::Maketext::GutsLoader"
"Locale::Maketext::TPJ13" "Locale::Script" "MIME::Base64"
"MIME::QuotedPrint" "Math::BigFloat" "Math::BigFloat::Trace" "Math::BigInt"
"Math::BigInt::Calc" "Math::BigInt::CalcEmu" "Math::BigInt::FastCalc"
"Math::BigInt::Trace" "Math::BigRat" "Math::Complex" "Math::Trig" "Memoize"
"Memoize::AnyDBM_File" "Memoize::Expire" "Memoize::ExpireFile"
"Memoize::ExpireTest" "Memoize::NDBM_File" "Memoize::SDBM_File"
"Memoize::Storable" "Module::Pluggable" "Module::Pluggable::Object"
"NDBM_File" "NEXT" "Net::Cmd" "Net::Config" "Net::Domain" "Net::FTP"
"Net::FTP::A" "Net::FTP::E" "Net::FTP::I" "Net::FTP::L"
"Net::FTP::dataconn" "Net::HTTP" "Net::HTTP::Methods" "Net::HTTP::NB"
"Net::HTTPS" "Net::LibIDN" "Net::NNTP" "Net::Netrc" "Net::POP3" "Net::Ping"
"Net::SMTP" "Net::SMTP::SSL" "Net::SSLeay" "Net::SSLeay::Handle"
"Net::Time" "Net::hostent" "Net::libnetFAQ" "Net::netent" "Net::protoent"
"Net::servent" "O" "Opcode" "POE" "POE::Component"
"POE::Component::Client::TCP" "POE::Component::Server::TCP" "POE::Driver"
"POE::Driver::SysRW" "POE::Filter" "POE::Filter::Block" "POE::Filter::Grep"
"POE::Filter::HTTPD" "POE::Filter::Line" "POE::Filter::Map"
"POE::Filter::RecordBlock" "POE::Filter::Reference"
"POE::Filter::Stackable" "POE::Filter::Stream" "POE::Kernel" "POE::Loop"
"POE::Loop::IO_Poll" "POE::Loop::PerlSignals" "POE::Loop::Select"
"POE::NFA" "POE::Pipe" "POE::Pipe::OneWay" "POE::Pipe::TwoWay" "POE::Queue"
"POE::Queue::Array" "POE::Resource" "POE::Resource::Aliases"
"POE::Resource::Events" "POE::Resource::Extrefs"
"POE::Resource::FileHandles" "POE::Resource::SIDs"
"POE::Resource::Sessions" "POE::Resource::Signals"
"POE::Resource::Statistics" "POE::Resources" "POE::Session" "POE::Wheel"
"POE::Wheel::Curses" "POE::Wheel::FollowTail" "POE::Wheel::ListenAccept"
"POE::Wheel::ReadLine" "POE::Wheel::ReadWrite" "POE::Wheel::Run"
"POE::Wheel::SocketFactory" "POSIX" "PerlIO" "PerlIO::encoding"
"PerlIO::scalar" "PerlIO::via" "PerlIO::via::QuotedPrint" "Pod::Checker"
"Pod::Escapes" "Pod::Find" "Pod::Functions" "Pod::Html" "Pod::InputObjects"
"Pod::LaTeX" "Pod::Man" "Pod::ParseLink" "Pod::ParseUtils" "Pod::Parser"
"Pod::Perldoc" "Pod::Perldoc::BaseTo" "Pod::Perldoc::GetOptsOO"
"Pod::Perldoc::ToChecker" "Pod::Perldoc::ToMan" "Pod::Perldoc::ToNroff"
"Pod::Perldoc::ToPod" "Pod::Perldoc::ToRtf" "Pod::Perldoc::ToText"
"Pod::Perldoc::ToTk" "Pod::Perldoc::ToXml" "Pod::PlainText" "Pod::Plainer"
"Pod::Select" "Pod::Simple" "Pod::Simple::BlackBox" "Pod::Simple::Checker"
"Pod::Simple::Debug" "Pod::Simple::DumpAsText" "Pod::Simple::DumpAsXML"
"Pod::Simple::HTML" "Pod::Simple::HTMLBatch" "Pod::Simple::HTMLLegacy"
"Pod::Simple::LinkSection" "Pod::Simple::Methody" "Pod::Simple::Progress"
"Pod::Simple::PullParser" "Pod::Simple::PullParserEndToken"
"Pod::Simple::PullParserStartToken" "Pod::Simple::PullParserTextToken"
"Pod::Simple::PullParserToken" "Pod::Simple::RTF" "Pod::Simple::Search"
"Pod::Simple::SimpleTree" "Pod::Simple::Subclassing" "Pod::Simple::Text"
"Pod::Simple::TextContent" "Pod::Simple::TiedOutFH"
"Pod::Simple::Transcode" "Pod::Simple::TranscodeDumb"
"Pod::Simple::TranscodeSmart" "Pod::Simple::XHTML"
"Pod::Simple::XMLOutStream" "Pod::Text" "Pod::Text::Color"
"Pod::Text::Overstrike" "Pod::Text::Termcap" "Pod::Usage" "SDBM_File"
"SVN::Base" "SVN::Client" "SVN::Core" "SVN::Delta" "SVN::Fs" "SVN::Ra"
"SVN::Repos" "SVN::Wc" "Safe" "Scalar::Util" "Scalar::Util::PP"
"Search::Dict" "SelectSaver" "SelfLoader" "Shell" "Socket" "Socket6"
"Socket::GetAddrInfo" "Storable" "Switch" "Symbol" "Sys::Hostname"
"Sys::Syslog" "Term::ANSIColor" "Term::Cap" "Term::Complete"
"Term::ReadKey" "Term::ReadLine" "Test" "Text::Abbrev" "Text::Balanced"
"Text::ParseWords" "Text::Soundex" "Text::Tabs" "Text::Wrap" "Thread"
"Thread::Queue" "Thread::Semaphore" "Tie::Array" "Tie::File" "Tie::Handle"
"Tie::Hash" "Tie::Hash::NamedCapture" "Tie::Memoize" "Tie::RefHash"
"Tie::Scalar" "Tie::StdHandle" "Tie::SubstrHash" "Time::HiRes"
"Time::Local" "Time::gmtime" "Time::localtime" "Time::tm" "UNIVERSAL" "URI"
"URI::Escape" "URI::Heuristic" "URI::IRI" "URI::QueryParam" "URI::Split"
"URI::URL" "URI::WithBase" "URI::_foreign" "URI::_generic" "URI::_idna"
"URI::_ldap" "URI::_login" "URI::_punycode" "URI::_query" "URI::_segment"
"URI::_server" "URI::_userpass" "URI::data" "URI::file" "URI::file::Base"
"URI::file::FAT" "URI::file::Mac" "URI::file::OS2" "URI::file::QNX"
"URI::file::Unix" "URI::file::Win32" "URI::ftp" "URI::gopher" "URI::http"
"URI::https" "URI::ldap" "URI::ldapi" "URI::ldaps" "URI::mailto" "URI::mms"
"URI::news" "URI::nntp" "URI::pop" "URI::rlogin" "URI::rsync" "URI::rtsp"
"URI::rtspu" "URI::sip" "URI::sips" "URI::snews" "URI::ssh" "URI::telnet"
"URI::tn3270" "URI::urn" "URI::urn::isbn" "URI::urn::oid"
"Unicode::Collate" "Unicode::Normalize" "Unicode::UCD" "User::grent"
"User::pwent" "WWW::RobotRules" "WWW::RobotRules::AnyDBM_File"
"XML::Parser" "XML::Parser::Expat" "XML::Parser::Style::Debug"
"XML::Parser::Style::Objects" "XML::Parser::Style::Stream"
"XML::Parser::Style::Subs" "XML::Parser::Style::Tree" "XSLoader" "a2p"
"attributes" "autodie" "autodie::exception" "autodie::exception::system"
"autodie::hints" "autouse" "base" "bigint" "bignum" "bigrat" "blib" "bytes"
"charnames" "common::sense" "constant" "deprecate" "diagnostics" "encoding"
"encoding::warnings" "feature" "fields" "filetest" "if" "integer" "less"
"lib" "locale" "lwpcook" "lwptut" "mro" "open.pod" "ops" "overload"
"overload::numbers" "overloading" "perl" "perl5004delta" "perl5005delta"
"perl5100delta" "perl5101delta" "perl5110delta" "perl5111delta"
"perl5112delta" "perl5113delta" "perl5114delta" "perl5115delta"
"perl5120delta" "perl5121delta" "perl5122delta" "perl5123delta"
"perl5124delta" "perl561delta" "perl56delta" "perl570delta" "perl571delta"
"perl572delta" "perl573delta" "perl581delta" "perl582delta" "perl583delta"
"perl584delta" "perl585delta" "perl586delta" "perl587delta" "perl588delta"
"perl589delta" "perl58delta" "perl590delta" "perl591delta" "perl592delta"
"perl593delta" "perl594delta" "perl595delta" "perlaix" "perlamiga"
"perlapi" "perlapio" "perlapollo" "perlartistic" "perlbeos" "perlbook"
"perlboot" "perlbot" "perlbs2000" "perlcall" "perlce" "perlcheat"
"perlclib" "perlcn" "perlcommunity" "perlcompile" "perlcygwin" "perldata"
"perldbmfilter" "perldebguts" "perldebtut" "perldebug" "perldelta"
"perldgux" "perldiag" "perldoc" "perldos" "perldsc" "perlebcdic"
"perlembed" "perlepoc" "perlfaq" "perlfaq1" "perlfaq2" "perlfaq3"
"perlfaq4" "perlfaq5" "perlfaq6" "perlfaq7" "perlfaq8" "perlfaq9"
"perlfilter" "perlfork" "perlform" "perlfreebsd" "perlfunc" "perlglossary"
"perlgpl" "perlguts" "perlhack" "perlhaiku" "perlhist" "perlhpux"
"perlhurd" "perlintern" "perlintro" "perliol" "perlipc" "perlirix" "perljp"
"perlko" "perllexwarn" "perllinux" "perllocale" "perllol" "perlmacos"
"perlmacosx" "perlmod" "perlmodinstall" "perlmodlib" "perlmodstyle"
"perlmpeix" "perlmroapi" "perlnetware" "perlnewmod" "perlnumber" "perlobj"
"perlop" "perlopenbsd" "perlopentut" "perlos2" "perlos390" "perlos400"
"perlpacktut" "perlperf" "perlplan9" "perlpod" "perlpodspec" "perlpolicy"
"perlport" "perlpragma" "perlqnx" "perlre" "perlreapi" "perlrebackslash"
"perlrecharclass" "perlref" "perlreftut" "perlreguts" "perlrepository"
"perlrequick" "perlreref" "perlretut" "perlriscos" "perlrun" "perlsec"
"perlsolaris" "perlstyle" "perlsub" "perlsymbian" "perlsyn" "perlthrtut"
"perltie" "perltoc" "perltodo" "perltooc" "perltoot" "perltrap" "perltru64"
"perltw" "perlunicode" "perlunifaq" "perluniintro" "perluniprops"
"perlunitut" "perlutil" "perluts" "perlvar" "perlvmesa" "perlvms" "perlvos"
"perlwin32" "perlxs" "perlxstut" "re" "sigtrap" "sort.pod" "strict" "subs"
"threads" "threads::shared" "utf8" "vars" "vendor_perl::AE"
"vendor_perl::AnyEvent" "vendor_perl::AnyEvent::AIO"
"vendor_perl::AnyEvent::BDB" "vendor_perl::AnyEvent::DNS"
"vendor_perl::AnyEvent::Debug" "vendor_perl::AnyEvent::Handle"
"vendor_perl::AnyEvent::Impl::EV" "vendor_perl::AnyEvent::Impl::Event"
"vendor_perl::AnyEvent::Impl::EventLib" "vendor_perl::AnyEvent::Impl::Glib"
"vendor_perl::AnyEvent::Impl::IOAsync" "vendor_perl::AnyEvent::Impl::Irssi"
"vendor_perl::AnyEvent::Impl::POE" "vendor_perl::AnyEvent::Impl::Perl"
"vendor_perl::AnyEvent::Impl::Qt" "vendor_perl::AnyEvent::Impl::Tk"
"vendor_perl::AnyEvent::Intro" "vendor_perl::AnyEvent::Socket"
"vendor_perl::AnyEvent::Strict" "vendor_perl::AnyEvent::TLS"
"vendor_perl::AnyEvent::Util" "vendor_perl::Async::MergePoint"
"vendor_perl::Authen::SASL" "vendor_perl::Authen::SASL::CRAM_MD5"
"vendor_perl::Authen::SASL::EXTERNAL" "vendor_perl::Authen::SASL::Perl"
"vendor_perl::Authen::SASL::Perl::ANONYMOUS"
"vendor_perl::Authen::SASL::Perl::CRAM_MD5"
"vendor_perl::Authen::SASL::Perl::DIGEST_MD5"
"vendor_perl::Authen::SASL::Perl::EXTERNAL"
"vendor_perl::Authen::SASL::Perl::GSSAPI"
"vendor_perl::Authen::SASL::Perl::LOGIN"
"vendor_perl::Authen::SASL::Perl::PLAIN" "vendor_perl::BDB"
"vendor_perl::Bundle::DBI" "vendor_perl::Compress::Raw::Bzip2"
"vendor_perl::Curses" "vendor_perl::Cwd" "vendor_perl::DBD::DBM"
"vendor_perl::DBD::ExampleP" "vendor_perl::DBD::File"
"vendor_perl::DBD::File::Developers" "vendor_perl::DBD::File::HowTo"
"vendor_perl::DBD::File::Roadmap" "vendor_perl::DBD::Gofer"
"vendor_perl::DBD::Gofer::Policy::Base"
"vendor_perl::DBD::Gofer::Policy::classic"
"vendor_perl::DBD::Gofer::Policy::pedantic"
"vendor_perl::DBD::Gofer::Policy::rush"
"vendor_perl::DBD::Gofer::Transport::Base"
"vendor_perl::DBD::Gofer::Transport::corostream"
"vendor_perl::DBD::Gofer::Transport::null"
"vendor_perl::DBD::Gofer::Transport::pipeone"
"vendor_perl::DBD::Gofer::Transport::stream" "vendor_perl::DBD::NullP"
"vendor_perl::DBD::Proxy" "vendor_perl::DBD::SQLite"
"vendor_perl::DBD::SQLite::Cookbook" "vendor_perl::DBD::Sponge"
"vendor_perl::DBI" "vendor_perl::DBI::Changes"
"vendor_perl::DBI::Const::GetInfo::ANSI"
"vendor_perl::DBI::Const::GetInfo::ODBC"
"vendor_perl::DBI::Const::GetInfoReturn"
"vendor_perl::DBI::Const::GetInfoType" "vendor_perl::DBI::DBD"
"vendor_perl::DBI::DBD::Metadata" "vendor_perl::DBI::DBD::SqlEngine"
"vendor_perl::DBI::DBD::SqlEngine::Developers"
"vendor_perl::DBI::DBD::SqlEngine::HowTo" "vendor_perl::DBI::FAQ"
"vendor_perl::DBI::Gofer::Execute" "vendor_perl::DBI::Gofer::Request"
"vendor_perl::DBI::Gofer::Response"
"vendor_perl::DBI::Gofer::Serializer::Base"
"vendor_perl::DBI::Gofer::Serializer::DataDumper"
"vendor_perl::DBI::Gofer::Serializer::Storable"
"vendor_perl::DBI::Gofer::Transport::Base"
"vendor_perl::DBI::Gofer::Transport::pipeone"
"vendor_perl::DBI::Gofer::Transport::stream" "vendor_perl::DBI::Profile"
"vendor_perl::DBI::ProfileData" "vendor_perl::DBI::ProfileDumper"
"vendor_perl::DBI::ProfileDumper::Apache" "vendor_perl::DBI::ProfileSubs"
"vendor_perl::DBI::ProxyServer" "vendor_perl::DBI::PurePerl"
"vendor_perl::DBI::SQL::Nano" "vendor_perl::DBI::Util::CacheMemory"
"vendor_perl::DBI::Util::_accessor" "vendor_perl::Digest::HMAC"
"vendor_perl::Digest::HMAC_MD5" "vendor_perl::Digest::HMAC_SHA1"
"vendor_perl::Digest::SHA1" "vendor_perl::EV" "vendor_perl::EV::MakeMaker"
"vendor_perl::EV::libev" "vendor_perl::Error" "vendor_perl::Error::Simple"
"vendor_perl::Event" "vendor_perl::Event::Lib"
"vendor_perl::Event::MakeMaker" "vendor_perl::Event::Watcher"
"vendor_perl::Event::generic" "vendor_perl::Event::group"
"vendor_perl::Event::idle" "vendor_perl::Event::io"
"vendor_perl::Event::signal" "vendor_perl::Event::timer"
"vendor_perl::Event::type" "vendor_perl::Event::var"
"vendor_perl::File::Spec" "vendor_perl::File::Spec::Cygwin"
"vendor_perl::File::Spec::Epoc" "vendor_perl::File::Spec::Functions"
"vendor_perl::File::Spec::Mac" "vendor_perl::File::Spec::OS2"
"vendor_perl::File::Spec::Unix" "vendor_perl::File::Spec::VMS"
"vendor_perl::File::Spec::Win32" "vendor_perl::GSSAPI"
"vendor_perl::GSSAPI::OID" "vendor_perl::GSSAPI::OID::Set"
"vendor_perl::GSSAPI::Status" "vendor_perl::Git" "vendor_perl::Glib"
"vendor_perl::Glib::BookmarkFile" "vendor_perl::Glib::Boxed"
"vendor_perl::Glib::CodeGen" "vendor_perl::Glib::Error"
"vendor_perl::Glib::Flags" "vendor_perl::Glib::GenPod"
"vendor_perl::Glib::Install::Files" "vendor_perl::Glib::KeyFile"
"vendor_perl::Glib::Log" "vendor_perl::Glib::MainLoop"
"vendor_perl::Glib::Markup" "vendor_perl::Glib::Object"
"vendor_perl::Glib::Object::Subclass" "vendor_perl::Glib::OptionContext"
"vendor_perl::Glib::OptionGroup" "vendor_perl::Glib::Param::Boolean"
"vendor_perl::Glib::Param::Double" "vendor_perl::Glib::Param::Enum"
"vendor_perl::Glib::Param::Flags" "vendor_perl::Glib::Param::Int"
"vendor_perl::Glib::Param::Int64" "vendor_perl::Glib::Param::String"
"vendor_perl::Glib::Param::UInt" "vendor_perl::Glib::Param::UInt64"
"vendor_perl::Glib::Param::Unichar" "vendor_perl::Glib::ParamSpec"
"vendor_perl::Glib::ParseXSDoc" "vendor_perl::Glib::Signal"
"vendor_perl::Glib::Type" "vendor_perl::Glib::Utils"
"vendor_perl::Glib::index" "vendor_perl::Glib::version"
"vendor_perl::Guard" "vendor_perl::HTML::Entities"
"vendor_perl::HTML::Filter" "vendor_perl::HTML::HeadParser"
"vendor_perl::HTML::LinkExtor" "vendor_perl::HTML::Parser"
"vendor_perl::HTML::PullParser" "vendor_perl::HTML::Tagset"
"vendor_perl::HTML::TokeParser" "vendor_perl::Heap"
"vendor_perl::Heap::Binary" "vendor_perl::Heap::Binomial"
"vendor_perl::Heap::Elem" "vendor_perl::Heap::Elem::Num"
"vendor_perl::Heap::Elem::NumRev" "vendor_perl::Heap::Elem::Ref"
"vendor_perl::Heap::Elem::RefRev" "vendor_perl::Heap::Elem::Str"
"vendor_perl::Heap::Elem::StrRev" "vendor_perl::Heap::Fibonacci"
"vendor_perl::IO::AIO" "vendor_perl::IO::Async"
"vendor_perl::IO::Async::ChildManager" "vendor_perl::IO::Async::Connector"
"vendor_perl::IO::Async::DetachedCode"
"vendor_perl::IO::Async::DetachedCode::FlatMarshaller"
"vendor_perl::IO::Async::DetachedCode::StorableMarshaller"
"vendor_perl::IO::Async::Handle"
"vendor_perl::IO::Async::Internals::SignalProxy"
"vendor_perl::IO::Async::Internals::TimeQueue"
"vendor_perl::IO::Async::Listener" "vendor_perl::IO::Async::Loop"
"vendor_perl::IO::Async::Loop::IO_Poll"
"vendor_perl::IO::Async::Loop::Poll" "vendor_perl::IO::Async::Loop::Select"
"vendor_perl::IO::Async::LoopTests" "vendor_perl::IO::Async::MergePoint"
"vendor_perl::IO::Async::Notifier" "vendor_perl::IO::Async::Resolver"
"vendor_perl::IO::Async::Sequencer" "vendor_perl::IO::Async::Signal"
"vendor_perl::IO::Async::Stream" "vendor_perl::IO::Async::Test"
"vendor_perl::IO::Async::Timer" "vendor_perl::IO::Async::Timer::Countdown"
"vendor_perl::IO::Async::Timer::Periodic" "vendor_perl::IO::Pty"
"vendor_perl::IO::Socket::SSL" "vendor_perl::IO::Tty"
"vendor_perl::IO::Tty::Constant" "vendor_perl::List::Util"
"vendor_perl::List::Util::PP" "vendor_perl::List::Util::XS"
"vendor_perl::Net::LibIDN" "vendor_perl::Net::SMTP::SSL"
"vendor_perl::Net::SSLeay" "vendor_perl::Net::SSLeay::Handle"
"vendor_perl::POE" "vendor_perl::POE::Component"
"vendor_perl::POE::Component::Client::TCP"
"vendor_perl::POE::Component::Server::TCP" "vendor_perl::POE::Driver"
"vendor_perl::POE::Driver::SysRW" "vendor_perl::POE::Filter"
"vendor_perl::POE::Filter::Block" "vendor_perl::POE::Filter::Grep"
"vendor_perl::POE::Filter::HTTPD" "vendor_perl::POE::Filter::Line"
"vendor_perl::POE::Filter::Map" "vendor_perl::POE::Filter::RecordBlock"
"vendor_perl::POE::Filter::Reference" "vendor_perl::POE::Filter::Stackable"
"vendor_perl::POE::Filter::Stream" "vendor_perl::POE::Kernel"
"vendor_perl::POE::Loop" "vendor_perl::POE::Loop::IO_Poll"
"vendor_perl::POE::Loop::PerlSignals" "vendor_perl::POE::Loop::Select"
"vendor_perl::POE::NFA" "vendor_perl::POE::Pipe"
"vendor_perl::POE::Pipe::OneWay" "vendor_perl::POE::Pipe::TwoWay"
"vendor_perl::POE::Queue" "vendor_perl::POE::Queue::Array"
"vendor_perl::POE::Resource" "vendor_perl::POE::Resource::Aliases"
"vendor_perl::POE::Resource::Events" "vendor_perl::POE::Resource::Extrefs"
"vendor_perl::POE::Resource::FileHandles"
"vendor_perl::POE::Resource::SIDs" "vendor_perl::POE::Resource::Sessions"
"vendor_perl::POE::Resource::Signals"
"vendor_perl::POE::Resource::Statistics" "vendor_perl::POE::Resources"
"vendor_perl::POE::Session" "vendor_perl::POE::Wheel"
"vendor_perl::POE::Wheel::Curses" "vendor_perl::POE::Wheel::FollowTail"
"vendor_perl::POE::Wheel::ListenAccept" "vendor_perl::POE::Wheel::ReadLine"
"vendor_perl::POE::Wheel::ReadWrite" "vendor_perl::POE::Wheel::Run"
"vendor_perl::POE::Wheel::SocketFactory" "vendor_perl::SVN::Base"
"vendor_perl::SVN::Client" "vendor_perl::SVN::Core"
"vendor_perl::SVN::Delta" "vendor_perl::SVN::Fs" "vendor_perl::SVN::Ra"
"vendor_perl::SVN::Repos" "vendor_perl::SVN::Wc"
"vendor_perl::Scalar::Util" "vendor_perl::Scalar::Util::PP"
"vendor_perl::Socket6" "vendor_perl::Socket::GetAddrInfo"
"vendor_perl::Term::ReadKey" "vendor_perl::XML::Parser"
"vendor_perl::XML::Parser::Expat" "vendor_perl::XML::Parser::Style::Debug"
"vendor_perl::XML::Parser::Style::Objects"
"vendor_perl::XML::Parser::Style::Stream"
"vendor_perl::XML::Parser::Style::Subs"
"vendor_perl::XML::Parser::Style::Tree" "vendor_perl::common::sense"
"vmsish" "warnings" "warnings::register"))
